In [1]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
import torch

In [3]:
torch.__version__

'2.0.0'

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply

In [5]:
df=pd.read_csv("california_housing_train.csv")

In [6]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [7]:
df.describe

<bound method NDFrame.describe of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population

In [8]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [9]:
#Dimension of scalar tensor
scalar.ndim

0

Get tensor back as Python int

In [10]:
scalar.item()

7

In [11]:
#vector
vector=torch.tensor([7,7,6])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

MATRIX

In [14]:
#MATRIX
MATRIX=torch.tensor([[1,2],
                    [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
 MATRIX[0][0]

tensor(1)

In [18]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                     [4,5,6],
                    [ 7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [73]:
TENSOR.ndim

3

In [19]:
 TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
#let's access 9
TENSOR[0][2][2]

tensor(9)

In [21]:
TENSOR.ndim

3

# Random tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.

Let's Create a random tensor of size (3, 4)

In [22]:
 # Create a random tensor of size (3, 4)
random_tensor = torch.rand (3, 4)
random_tensor

tensor([[0.7512, 0.8997, 0.8633, 0.0159],
        [0.1124, 0.5336, 0.3106, 0.1274],
        [0.7431, 0.7304, 0.8886, 0.7926]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.dtype

torch.float32

### Create a random tensor with similar shape to an image tensor

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensor

In [26]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Some Arithmatic operations on tensors like any numpy array

In [28]:
zeros*ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros+ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [30]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=100, step=7)
one_to_ten

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

### Convert any tensor into zeros tensor

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Convert float 32 bit tensor into 16 bit tensor datatype

In [32]:
 # Float 32 tensor
float_32_tensor = torch.tensor ([3.0, 6.0, 9.0],
dtype=None, #what datatype is the tensor (e.g. float32 )
device=None, # What device is your tensor on
requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type (torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
# just for try
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_64_tensor = torch.tensor ([3.0, 6.0, 9.0], dtype=torch.int32)


In [37]:
int_64_tensor*float_32_tensor

tensor([ 9., 36., 81.])

## Tensor Attribute

### Getting information from tensors
1. Tensors not right datatype to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device

In [38]:
some_tensor=torch.rand(3,3)
some_tensor

tensor([[0.5193, 0.5217, 0.5752],
        [0.6838, 0.4677, 0.2654],
        [0.2897, 0.6663, 0.4418]])

In [39]:
# Find out details about some tensor
print (some_tensor)
print (f"Datatype of tensor: {some_tensor.dtype}")
print (f"Shape of tensor: {some_tensor.shape}")
print (f"Device tensor is on: {some_tensor.device}")

tensor([[0.5193, 0.5217, 0.5752],
        [0.6838, 0.4677, 0.2654],
        [0.2897, 0.6663, 0.4418]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 3])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)


Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [40]:
# create a tensor
tensor1=torch.tensor([10,50,23])
tensor1

tensor([10, 50, 23])

In [41]:
#Addition
tensor1+10
#OR
torch.add(10,tensor1)

tensor([20, 60, 33])

In [42]:
# Subtraction
tensor1-10

tensor([ 0, 40, 13])

In [43]:
#Division
tensor1/10

tensor([1.0000, 5.0000, 2.3000])

In [44]:
#Multiplication
tensor1*10
#OR
torch.mul(10,tensor1)

tensor([100, 500, 230])

In [45]:
# Multiplication of Matrix
MATRIX1=torch.tensor([[1,2],
                     [3,4]])

MATRIX2=torch.tensor([[5,6],
                     [7,8]])

In [46]:
MATRIX1*MATRIX2

tensor([[ 5, 12],
        [21, 32]])

### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning: 
1. Element-wise multiplication
2. Matrix mutliplication

In [47]:
# Element wise multiplication
print ("MATRIX1 * MATRIX2")
print (f"Equals: {MATRIX1*MATRIX2}")

MATRIX1 * MATRIX2
Equals: tensor([[ 5, 12],
        [21, 32]])


In [48]:
# Matrix multiplication

torch.matmul(MATRIX1, MATRIX2)


tensor([[19, 22],
        [43, 50]])

In [49]:
#Shortcut to perform matrix multiplication
MATRIX1 @ MATRIX2

tensor([[19, 22],
        [43, 50]])

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The inner dimensions must match:           
(3, 2) @ (3, 2) won't work                  
(2, 3) @ (3, 2) will work                      
(3, 2) @ (2, 3) will work                               
2. The resulting matrix has the shape of the outer dimensions:                                  
(2, 3) @ (3, 2)-> (2, 2)                           
(3, 2) @ (2, 3) -> (3, 3)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.
A transpose switches the axes or dimensions of a given tensor.

In [50]:
MATRIX1.T

tensor([[1, 3],
        [2, 4]])

 ## Finding the min, max, mean, sum, etc (tensor aggregation)

In [51]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
# Find the min.
torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
# Find the mean note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type (torch.float32)), x.type (torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [56]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Find the position in tensor that has the minimum value with argmin () -> returns index position of targt tensor where the minimum value occurs
x.argmin()

tensor(0)

In [58]:
# Find the position in tensor that has the maximum value with argmax ()
x.argmax ( )

tensor(9)

In [59]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors               
● Reshaping - reshapes an input tensor to a defined shape                   
● View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor                    
• Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)                        
• Squeeze - removes all 1 dimensions from a tensor                                
● Unsqueeze - add a 1 dimension to a target tensor                                 
● Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [60]:
x=torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
x.dtype,x.shape

(torch.float32, torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshaped = x.reshape (1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
x_reshaped.ndim

2

In [64]:
# Change the view
z = x.view (1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input
z[0][0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [67]:
# torch.squeeze() removes all single dimensions from a target tensor

print (f"Previous tensor: {x_reshaped}")
print (f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped

x_squeezed = x_reshaped.squeeze()
print (f"\nNew tensor: {x_squeezed}")
print (f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [68]:
# torch.unsqueeze() adds a single dimension to a target tensor at a specific dim (dimention)

print (f"Previous target: {x_squeezed}")
print (f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze (dim=0)
print (f"\nNew tensor: {x_unsqueezed}")
print (f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [69]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand (size=(224, 224, 3)) # [height, width, colour_channels]
# Permute the original tensor to rearrange the axis (or dim) order 
x_permuted = x_original.permute (2, 0, 1) # shifts axis 0->1, 1->2, 2->0

In [70]:
print (f"Previous shape: {x_original.shape}")
print (f"New shape: {x_permuted.shape}") # ([color channels, hight, width])

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [71]:
x_original[0,1,1]=4

In [72]:
x_permuted[1,0,1] #hence, the shape has been changed 

tensor(4.)