In [23]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt
import numpy as np
from torch.autograd import Variable
# Check PyTorch version
torch.__version__

'2.0.0'

## Creating data for our neural network

In [24]:
def get_data():
    train_X=np.asarray([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,7.042,10.791,5.313,7.997,5.654,9.27,3.1])
    train_Y=np.asarray([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,2.827,3.465,1.65,2.904,2.42,2.94,1.3])
    dtype=torch.FloatTensor
    #tensor = torch.from_numpy(array) 
    # warning: when converting from numpy -> pytorch, 
    # pytorch reflects numpy's default datatype of float 64 unless specified otherwise
    X=Variable(torch.from_numpy(train_X).type(dtype),requires_grad=False).view(17,1)
    y=Variable(torch.from_numpy(train_Y).type(dtype),requires_grad=False)
    return X,y
    

In [25]:
X,y = get_data()

In [26]:
X,y

(tensor([[ 3.3000],
         [ 4.4000],
         [ 5.5000],
         [ 6.7100],
         [ 6.9300],
         [ 4.1680],
         [ 9.7790],
         [ 6.1820],
         [ 7.5900],
         [ 2.1670],
         [ 7.0420],
         [10.7910],
         [ 5.3130],
         [ 7.9970],
         [ 5.6540],
         [ 9.2700],
         [ 3.1000]]),
 tensor([1.7000, 2.7600, 2.0900, 3.1900, 1.6940, 1.5730, 3.3660, 2.5960, 2.5300,
         1.2210, 2.8270, 3.4650, 1.6500, 2.9040, 2.4200, 2.9400, 1.3000]))

## Creating learnable parameters 

In [27]:
def get_weights():
    w=Variable(torch.randn(1),requires_grad=True )
    b=Variable(torch.randn(1),requires_grad=True )
    return w,b

In [28]:
w,b=get_weights()
w,b

(tensor([0.8386], requires_grad=True), tensor([1.9043], requires_grad=True))

## Network Implementation

In [29]:
def simple_network(x):
    y_pred=torch.matmul(x,w)+b
    return y_pred

In [30]:
y_pred=simple_network(X)
y_pred

tensor([ 4.6716,  5.5941,  6.5165,  7.5312,  7.7157,  5.3995, 10.1048,  7.0884,
         8.2691,  3.7215,  7.8096, 10.9535,  6.3597,  8.6105,  6.6456,  9.6780,
         4.5039], grad_fn=<AddBackward0>)

## Loss function

#### We need to define a function which tells the model how close its predictions are to the actual values. Since this is a regression problem, we use a loss function called sum of squared error. We take the difference between the predicted y and the actual y and square it. SSE helps the model to understand how close the predicted Values are to the actual values.

In [31]:
def loss_fn(y,y_pred):
    loss=(y_pred-y).pow(2).sum()
    for param in [w,b]:
        if not param.grad is None: 
            param.grad.data.zero_()
    loss.backward()
    return loss.item()

In [32]:
loss_fn(y,y_pred)

420.1586608886719

## Optimize the neural network

In [33]:
def optimize(learning_rate):
    w.data-=learning_rate * w.grad.data
    b.data-=learning_rate * b.grad.data    
    return w.data,b.data

In [34]:
w.data

tensor([0.8386])

In [35]:
b.data

tensor([1.9043])

In [36]:
for i in range (500):
    y_pred =simple_network(X)
    loss=loss_fn(y,y_pred)
    if i%50==0:
        print(loss)
optimize(learning_rate=5)

420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719
420.1586608886719


(tensor([-5588.3403]), tensor([-807.5677]))

## what Makes DL so Powerful,
#### is that fact that the entire function the we wrote in previous cells can be writen in a single line of code as follows:


In [37]:
from torch.nn import Linear
myLayer =Linear(in_features =10,out_features =5,bias=True)

In [38]:
inp=Variable(torch.randn(1,10))
myLayer=Linear(in_features =10,out_features =5,bias=True)
myLayer(inp)

tensor([[ 0.0645,  0.0818,  0.0089,  0.4453, -0.4505]],
       grad_fn=<AddmmBackward0>)

In [39]:
myLayer.weight 

Parameter containing:
tensor([[ 0.1112,  0.1045, -0.0183,  0.2414, -0.1427,  0.2798,  0.2729,  0.1575,
          0.1983,  0.2472],
        [-0.2179, -0.2557, -0.0267, -0.0157,  0.1003, -0.0562,  0.1985, -0.1210,
          0.2425, -0.2217],
        [ 0.1255,  0.2703, -0.2643, -0.1421, -0.1277,  0.2168, -0.2214,  0.1792,
         -0.1496,  0.2927],
        [-0.0065,  0.2961, -0.2108, -0.2231,  0.1502,  0.2570,  0.3150,  0.1791,
          0.0942,  0.1544],
        [ 0.1887, -0.2315, -0.0588,  0.2360, -0.1995,  0.1330,  0.2581, -0.0552,
          0.1616,  0.2068]], requires_grad=True)

In [40]:
myLayer.bias

Parameter containing:
tensor([ 0.2246, -0.2843,  0.1514, -0.1146, -0.2727], requires_grad=True)

### One Simple approach is passing the output of one layer to another layer:

In [41]:
myLayer1=Linear(10,5)
myLayer2=Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[0.3409, 0.4363]], grad_fn=<AddmmBackward0>)

##  Some of popular Non-Linear function in Deep Learning

 * Sigmoid
 * Tanh
 * ReLU - f(x) =max(0,x)
 * Leaky ReLU
 
 


In [44]:
#ReLu in pytorch
sample_data = (torch.Tensor([[1,2,-1,-1]]))
myRelu=nn.ReLU()
myRelu(sample_data)

tensor([[1., 2., 0., 0.]])