## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [1]:
 # Create a tensor
import torch
x = torch.arange (1, 10).reshape (1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
# Let's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [4]:
# Let's index on most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [5]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [6]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [7]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[0, 1, 1]

tensor(5)

# PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> torch. from_numpy (ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy ()


In [12]:
#NumPy array to tensor
import torch
import numpy as np
array = np.arange (1.0, 8.0)
tensor = torch.from_numpy(array) 
# warning: when converting from numpy -> pytorch, 
# pytorch reflects numpy's default datatype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [18]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float32)

In [13]:
# Change the value of array, what will this do to “tensor?
array = array + 1
array,tensor    #modification in base array doesn't reflect in newly formed tensor.

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [14]:
# Tensor to NumPy array
tensor = torch.ones (7)
numpy_tensor = torch.Tensor.numpy(tensor)
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [16]:
numpy_tensor.dtype,tensor.dtype

(dtype('float32'), torch.float32)

In [19]:
# Change the tesnor, what happens to “numpy_tensor’?
tensor = tensor + 1
tensor, numpy_tensor
#modification in base tensor doesn't reflect in newly formed array.

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

 * In short how a neural network learns:

* “start with random numbers -> tensor operations -> update random numbers to try and
 make them better representations of the data -> again -> again -> again..."

* To reduce the randomness in neural networks and PyTorch comes the concept of a
"random seeds".

* Essentially what the random seed does is "flavour" the randomness.



In [22]:
torch.rand(3,4) #It will produce a [3 X 4] matrix of random numbers every time it executed.

tensor([[0.9119, 0.7722, 0.1620, 0.0827],
        [0.7169, 0.6130, 0.3611, 0.2599],
        [0.4824, 0.5682, 0.4703, 0.2585]])

In [26]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)

print(random_tensor_B)

print(random_tensor_A == random_tensor_B)


tensor([[0.4976, 0.4263, 0.0301, 0.3668],
        [0.2266, 0.6256, 0.0215, 0.2184],
        [0.5903, 0.5593, 0.2108, 0.9640]])
tensor([[0.1452, 0.4641, 0.9223, 0.9596],
        [0.8330, 0.0660, 0.1284, 0.1746],
        [0.6936, 0.6821, 0.2770, 0.6925]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [32]:
# Let's make some random but reproducible tensors

# Set the random seed

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C =torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

# After selecting a manual seed it will produce same number.
# it is called a seed bcoz we can produce some same number with the help of it, 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])